spring:
  application:
    name: orderservice

  datasource:
    url: ${ORDER_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log-path: classpath:changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show_sql: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVICES:localhost:9092}
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.innowise.orderservice.dto.event

app:
  service:
    user-service:
      url: ${USER_SERVICE_URL:http://localhost:8081}

  kafka:
    topics:
      payment-events: payment-events

logging:
  level:
    root: INFO

resilience4j:
  circuitbreaker:
    instances:
      userService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s